import { NarrativeTheme, CharacterAttributes } from '../types';

// Predefined lists by narrative theme. Defined for social relations/story arcs.
export const characterPresets: Record<NarrativeTheme, CharacterAttributes> = {
  Family: {
    races: ['Human'],
    professions: ['Parent','Child','Sibling','Relative','Guardian','Family Solicitor','Hausmeister'],
    alignments: ['Supportive','Distant','Antagonistic','Neutral','Matriarchal','Patriarchal'],
    personalityTraits: ['Loving','Jealous','Protective','Resentful','Nurturing','Manipulative'],
    backgrounds: ['Nuclear family','Blended family','Orphan','Abusive home','Wealthy household','Working class'],
    magicSystems: ['Inherited Bloodline','Household Spirits','Cursed Heritage','None (Mundane)'],
    socialStandings: ['Old Money','New Money','Fallen Nobility','Middle Class','Poverty-stricken'],
    powerSources: ['Ancestral Bond','Family Relic','Emotional Trauma','Legacy'],
    vibes: ['Cozy','Stifling','Nostalgic','Elegant','Shabby'],
    paradoxes: ['The Loving Oppressor','The Silent Protector','The Spoiled Ascetic'],
  },
  Romance: {
    races: ['Human','Elf','Vampire'],
    professions: ['Poet','Artist','Musician','Florist','Matchmaker','Rival Suitor'],
    alignments: ['Devoted','Fickle','Obsessive','Platonic','Chivalrous'],
    personalityTraits: ['Passionate','Shy','Jealous','Devoted','Cynical','Idealistic'],
    backgrounds: ['High school sweethearts','Arrangement','Online meeting','Forbidden love','Long-distance'],
    magicSystems: ['Soul-binding','Aphrodisiac Alchemy','Empathic Resonance','Fated Connection'],
    socialStandings: ['Socialite','Outcast','Working Class','Celebrity'],
    powerSources: ['Heartbreak','Unwavering Devotion','True Love\'s Kiss','Obsession'],
    vibes: ['Dreamy','Intense','Graceful','Sultry','Melancholic'],
    paradoxes: ['The Lonely Romantic','The Faithless Devotee','The Heartbreaking Healer'],
  },
  Fantasy: {
    races: ['Human','Elf','Dwarf','Orc','Fairy','Half-Giant','Dragonkin'],
    professions: ['Archmage','Paladin','Sellsword','Alchemist','Beastmaster','Bard'],
    alignments: ['Lawful Good','Chaotic Neutral','True Neutral','Lawful Evil','Neutral Good'],
    personalityTraits: ['Stoic','Whimsical','Ambitious','Pious','Mysterious','Greedy'],
    backgrounds: ['Apothecary Apprentice','Royal Guard','Street Urchin','Banished Noble','Temple Orphan'],
    magicSystems: ['Vancian (Spell Slots)','Wild Magic','Runic Inscription','Elemental Channeling','Necromancy'],
    socialStandings: ['Crowned Royalty','Lesser Nobility','Free Merchant','Peasantry','Outlaw'],
    powerSources: ['Ley Lines','Ancient Artifact','Pact with Entity','Deep Study','Innate Blood'],
    vibes: ['Ethereal','Gritty','High-Magic','Rustic','Crystalline'],
    paradoxes: ['The Cowardly Knight','The Illiterate Scholar','The Healer who kills'],
  },
  Cyberpunk: {
    races: ['Human','Cyborg','AI Instance','Bio-engineered Variant'],
    professions: ['Netrunner','Solo','Techie','Fixer','Corpo Agent','Medline Runner'],
    alignments: ['Anti-Corporate','Sell-out','Chaos-bringer','Survivalist','Idealist'],
    personalityTraits: ['Cynical','Aggressive','Calculated','Wired','Jaded','Optimistic'],
    backgrounds: ['Corporate Lab Rat','Street-bred','Military Veteran','Ex-Executive'],
    magicSystems: ['Data Manipulation','Technomancy','Neural Grafting','Chemical Overdrive'],
    socialStandings: ['Corporate Elite','Salaryman','Lower Block Resident','Street Trash'],
    powerSources: ['Cybernetic Implants','Neural Link','Experimental Drugs','Black Market Tech'],
    vibes: ['Neon-drenched','Chrome','Rain-slicked','Industrial','Glitchy'],
    paradoxes: ['The Moral Mercenary','The Analog Netrunner','The Empathic AI'],
  },
  Horror: {
    races: ['Human','Ghost','Vampire','Ghoul','Possessed Body'],
    professions: ['Occultist','Exorcist','Asylum Doctor','Gravedigger','Slasher','Survivor'],
    alignments: ['Traumatized','Malignant','Heroic','Complicit','Nihilistic'],
    personalityTraits: ['Quiet','Obsessive','Paranoid','Phobic','Sadistic','Brave'],
    backgrounds: ['Sanatorium Resident','Cult Escapee','Ancient Curse','Forensic Specialist'],
    magicSystems: ['Blood Sacrificial','Forbidden Lore','Eldritch Summoning','Psychic Trauma'],
    socialStandings: ['Pariah','Secret Society Elite','Normal Citizen','Missing Person'],
    powerSources: ['Fear','Pain','Ancient Evil','Delusion','Vitality'],
    vibes: ['Gothic','Grotesque','Sterile','Decaying','Claustrophobic'],
    paradoxes: ['The Rational Ghost-hunter','The Gentle Murderer','The Religious Nihilist'],
  },
  Noir: {
    races: ['Human'],
    professions: ['Private Investigator','Femme Fatale','Corrupt Cop','Jazz Musician','Mob Enforcer'],
    alignments: ['Jaded','Honest (Foolishly)','Dirty','Neutral','Idealistic'],
    personalityTraits: ['World-weary','Sarcastic','Eloquent','Brooding','Smooth'],
    backgrounds: ['War Vet','Disgraced Officer','Small Town Runaway','Crime Scene Cleaner'],
    magicSystems: ['Fatalism','Smokescreen Illusion','Luck Manipulation','Hard-boiled Intuition'],
    socialStandings: ['Upper Crust','Gutter-dweller','Police Force','Underworld'],
    powerSources: ['Pure Grit','Cigarettes & Whiskey','Desperation','Secret Knowledge'],
    vibes: ['Monochrome','Shadowy','Rainy','Tobacco-stained','Sharp'],
    paradoxes: ['The Honest Thief','The Optimistic Cynic','The Soft-hearted Enforcer'],
  },
  Thriller: {
    races: ['Human','Augmented Human','Sleeper Agent'],
    professions: ['Negotiator','Profiler','Bodyguard','Blackmailer','Investigative Reporter','Fixer'],
    alignments: ['Cornered','Ruthless','Protective','Obsessive','Pragmatic'],
    personalityTraits: ['Hyper-vigilant','Controlled','Manipulative','Determined','Secretive','Impulsive'],
    backgrounds: ['Witness Protection','Botched Operation','Corporate Leak','Family Secret','Political Cover-up'],
    magicSystems: ['Adrenaline Surge','Pattern Recognition','Social Pressure','None'],
    socialStandings: ['Public Figure','Unknown Asset','Security Detail','Compromised Insider'],
    powerSources: ['Leverage','Fear','Urgency','Blackmail','Evidence'],
    vibes: ['Breathless','Tight','Paranoid','Modern-noir','High-pressure'],
    paradoxes: ['The Honest Manipulator','The Fearless Coward','The Protector who endangers everyone'],
  },
  // Adding default for other themes
  Mystery: {
    races: ['Human'],
    professions: ['Consultant','Detective','Suspect','Witness','Medical Examiner'],
    alignments: ['Unyielding','Compromised','Curious','Vigilante'],
    personalityTraits: ['Analytical','Observant','Deceptive','Tenacious','Aloof'],
    backgrounds: ['Cold Case Survivor','Intelligence Agency','Small Town Gossip'],
    magicSystems: ['Deductive Trance','Clairvoyance','Object Psychometry','None'],
    socialStandings: ['Professional','Outsider','High Society','Government'],
    powerSources: ['Evidence','Logic','Hyper-focus','Intuition'],
    vibes: ['Clinical','Tense','Suspicious','Atmospheric'],
    paradoxes: ['The Blind Observer','The Criminal Detective','The Accidental Witness'],
  },
  Adventure: {
    races: ['Human','Half-Elf','Stray'],
    professions: ['Surveyor','Treasure Hunter','Archaeologist','Navigator','Beast Tamer'],
    alignments: ['Bold','Reckless','Loyal','Resourceful'],
    personalityTraits: ['Enthusiastic','Pragmatic','Daring','Curious','Hardy'],
    backgrounds: ['Shipwreck Survivor','Map-maker','Ex-Soldier','Nomad'],
    magicSystems: ['Pathfinding','Nature Bonding','Survival Instinct','Artifact Mastery'],
    socialStandings: ['Wanderer','Guild Member','Disgrace','Legend'],
    powerSources: ['Adrenaline','Ancient Relic','Friendship','Willpower'],
    vibes: ['Vibrant','Rugged','Expansive','Exciting'],
    paradoxes: ['The Home-sick Explorer','The Clumsy Acrobat','The Pacifist Warrior'],
  },
  Drama: {
    races: ['Human'],
    professions: ['Philanthropist','Scandalmonger','Matriarch','Disgraced Heir','Doctor'],
    alignments: ['Self-Serving','Duty-Bound','Manipulative','Empathetic'],
    personalityTraits: ['Dramatic','Calculating','Passionate','Reserved','Charismatic'],
    backgrounds: ['Old Scandal','Public Fall from Grace','Political Dynasty'],
    magicSystems: ['Social Influence','Emotional Manipulation','Presence','None'],
    socialStandings: ['elite','middle class','disgraced','rising star'],
    powerSources: ['Reputation','Secret Information','Wealth','Charisma'],
    vibes: ['Opulent','Tense','Stifling','Melodramatic'],
    paradoxes: ['The Truth-telling Liar','The Cruel Philanthropist','The Silent Actor'],
  },
  Comedy: {
    races: ['Human','Bizarre Creature'],
    professions: ['Fool','Mishap-prone Baker','Over-confident Intern','Reluctant Hero'],
    alignments: ['Mischievous','Well-meaning','Chaotic','Deadpan'],
    personalityTraits: ['Absurd','Optimistic','Dry','Hyperactive','Oblivious'],
    backgrounds: ['Accidental Success','Series of Unfortunate Events'],
    magicSystems: ['Slapstick Physics','Luck','Bizarre Coincidence','None'],
    socialStandings: ['The Butt of the Joke','Local Legend','Ordinary Guy'],
    powerSources: ['Misunderstanding','Incompetence','Confused Confidence'],
    vibes: ['Whimsical','Colorful','Absurd','Lighthearted'],
    paradoxes: ['The Depressed Clown','The Competent Idiot','The Unlucky Lucky-man'],
  },
  Historical: {
    races: ['Human'],
    professions: ['Scribe','Blacksmith','Courtier','Mercenary','Peasant','Oracle'],
    alignments: ['Traditional','Rebellious','Pious','Honor-bound'],
    personalityTraits: ['Stoic','Faithful','Hardworking','Proud','Resourceful'],
    backgrounds: ['Guild Trained','Military Service','Monastic Life'],
    magicSystems: ['Alchemy','Superstition','Divine Favor','None'],
    socialStandings: ['Clergy','Nobility','Peasantry','Outcast'],
    powerSources: ['Faith','Lineage','Hard Work','Divine Will'],
    vibes: ['Grounded','Dusty','Grand','Authentic'],
    paradoxes: ['The Atheist Priest','The Cowardly General','The Educated Serf'],
  },
  Western: {
    races: ['Human'],
    professions: ['Bounty Hunter','Outlaw','Lawman','Prospector','Drifter'],
    alignments: ['Lawful','Uncivilized','Vengeful','Mercenary'],
    personalityTraits: ['Grizzled','Laconic','Tough','Vengeful','Rugged'],
    backgrounds: ['Civil War Vet','Frontier Life','Outlaw Gang'],
    magicSystems: ['Quick-draw Intuition','Desert Mysticism','Gun-smoke Divination'],
    socialStandings: ['The Law','Wanted','Homesteader','Drifter'],
    powerSources: ['Silver','Lead','Resolve','Land'],
    vibes: ['Dusty','Arid','Lonesome','Violent'],
    paradoxes: ['The Pacifist Gunman','The Civilized Outlaw','The Holy Drifter'],
  },
  'Sci-Fi': {
    races: ['Human','Android','Alien (Gray)','Synthetic Brain'],
    professions: ['Astro-Engineer','Void Pilot','Exo-Biologist','Space Marine','Smuggler'],
    alignments: ['Scientific','Expansionist','Isolationist','Utilitarian'],
    personalityTraits: ['Logical','Curious','Detached','Adaptive','Experimental'],
    backgrounds: ['Earth-born','Colony-raised','Deep Space Station'],
    magicSystems: ['Quantum Manipulation','Nanotech','psionics','Hard Science'],
    socialStandings: ['Citizen','Spacer','Refugee','Corporate Asset'],
    powerSources: ['Fusion Core','Neural Network','Bio-mass','Information'],
    vibes: ['Sleek','Clinical','Void','High-tech'],
    paradoxes: ['The Luddite Robot','The Religious Scientist','The Empathic AI'],
  },
  'Supernatural': {
    races: ['Vampire','Spirit','Witch','Demon','Werewolf','Hunter'],
    professions: ['Guardian of the Veil','Relic Seeker','Shadow Hunter','Cursed Mortal'],
    alignments: ['Hidden','Ancient','Protective','Corrupting'],
    personalityTraits: ['Mysterious','Ancient','Hungry','Duty-bound','Secrets-keeper'],
    backgrounds: ['The Great War of Shadows','Awakened','Cursed Lineage'],
    magicSystems: ['Ritualistic','Innate Darkness','Sacramental','Chaos'],
    socialStandings: ['The Hidden World','Society Elite','Outcast'],
    powerSources: ['The Veil','Blood','Ancient Pact','Fear'],
    vibes: ['Eerie','Nocturnal','Gothic','Hidden'],
    paradoxes: ['The Vegetarian Vampire','The Kind Demon','The Mortal Immortal'],
  },
  'Post-Apocalyptic': {
    races: ['Survivor','Mutant','Ghoul','Scavenger'],
    professions: ['Scrapper','Wasteland Guide','Rad-Medic','Warlord','Tinker'],
    alignments: ['Merciless','Communal','Desperate','Neutral'],
    personalityTraits: ['Pragmatic','Sullen','Determined','Wild','Calculating'],
    backgrounds: ['Pre-fall Historian','Vault Dweller','Wilderness Born'],
    magicSystems: ['Radiation Manipulation','Junk-tech','Psionic Mutation','None'],
    socialStandings: ['Scavenger','Tribal Elite','Lone Wolf','Settler'],
    powerSources: ['Scrap','Recycled Energy','Mutation','Survival'],
    vibes: ['Rust','Decay','Arid','Desolate'],
    paradoxes: ['The Civilized Mutant','The Kind Raider','The Hopeful Nihilist'],
  },
  Dystopian: {
    races: ['Citizen','Sub-citizen','Enforcer','Drone'],
    professions: ['Censor','Information Dealer','Rebel','Propagandist','Peacekeeper'],
    alignments: ['Compliant','Rebellious','Opportunistic','Neutral'],
    personalityTraits: ['Oppressed','Vigilant','Secretive','Defiant','Numb'],
    backgrounds: ['Work Camp','Elite District','Underground Resistance'],
    magicSystems: ['Mass Surveillance','Thought Control','Biometric Hacking'],
    socialStandings: ['Alpha Grade','Epsilon Grade','Resistance','System Admin'],
    powerSources: ['Information','Fear','Data','Control'],
    vibes: ['Sterile','Oppressive','Neon-cold','Surveillance'],
    paradoxes: ['The Happy Slave','The Rebel Officer','The Truth-telling Spy'],
  },
  Utopian: {
    races: ['Human','Perfected Being','AI Caretaker'],
    professions: ['Philosopher','Designer','Gardener','Peace-keeper','Artist'],
    alignments: ['Harmonious','Stagnant','Enlightened','Protective'],
    personalityTraits: ['Serene','Bored','Curious','Empathic','Idealistic'],
    backgrounds: ['The Great Peace','Legacy of War','Designer Birth'],
    magicSystems: ['Harmonic Resonance','Ecology Control','Creation'],
    socialStandings: ['Equal','Visionary','Elder'],
    powerSources: ['Sunlight','Community','Joy','Idea'],
    vibes: ['Lush','Symmetric','Peaceful','Bright'],
    paradoxes: ['The Violent Pacifist','The Sad Perfect-being','The Unhappy Citizen'],
  },
  Crime: {
    races: ['Human'],
    professions: ['Enforcer','Safe-cracker','Con Artist','Undercover Agent','Boss'],
    alignments: ['Loyal to the Code','Selfish','Moral','Calculating'],
    personalityTraits: ['Cold','Charismatic','Street-smart','Deceptive','Loyal'],
    backgrounds: ['The Streets','Prison Yard','White Collar Elite'],
    magicSystems: ['Social Engineering','Street Magic (Sleight of Hand)','Intuition','None'],
    socialStandings: ['Mob Heir','Street Thug','Middle Man','Police'],
    powerSources: ['Blackmail','Cash','Fear','Connections'],
    vibes: ['Gritty','Tense','Smoky','Hidden'],
    paradoxes: ['The Honest Criminal','The Cowardly Thug','The Rich Beggar'],
  },
  Political: {
    races: ['Human','Diplomat Alien'],
    professions: ['Senator','Advisor','Spy','Journalist','Revolutionary','Monarch'],
    alignments: ['Ideological','Pragmatic','Ambitious','Diplomatic'],
    personalityTraits: ['Eloquent','Manipulative','Stoic','Idealistic','Charming'],
    backgrounds: ['Dynasty Child','Student Activist','Intelligence Officer'],
    magicSystems: ['Rhetoric','Presence','Network Influence','Subterfuge'],
    socialStandings: ['Elite','Exile','Commoner','King-maker'],
    powerSources: ['The People','The Crown','The Secret','The Budget'],
    vibes: ['Stifling','Grand','Clinical','Calculated'],
    paradoxes: ['The Truthful Politician','The Unambitious King','The Silent Orator'],
  },
  'Slice-of-Life': {
    races: ['Human'],
    professions: ['Barista','Student','Office Worker','Neighbor','Cousin'],
    alignments: ['Normal','Quirky','Supportive','Neutral'],
    personalityTraits: ['Relatable','Awkward','Friendly','Tired','Ambitious'],
    backgrounds: ['Small Town','Urban Apartment','Corporate Office'],
    magicSystems: ['Small Joys','Luck','None'],
    socialStandings: ['Average Joe','Struggling Artist','Newcomer'],
    powerSources: ['Coffee','Friendship','Routine','Hard Work'],
    vibes: ['Warm','Mundane','Relatable','Cozy'],
    paradoxes: ['The Interesting Boring-person','The Tired Optimist','The Quiet Large-personality'],
  },
  'Coming-of-Age': {
    races: ['Human'],
    professions: ['Student','Intern','Runaway','Apprentice','Aspiring Artist'],
    alignments: ['Developing','Naive','Rebellious','Searcher'],
    personalityTraits: ['Insecure','Hopeful','Rebellious','Curious','Vulnerable'],
    backgrounds: ['The Neighborhood','Family Home','First Job'],
    magicSystems: ['Potential','Awakening','Self-discovery'],
    socialStandings: ['Youth','Junior','Inheritor'],
    powerSources: ['Experience','Emotions','First-time','Ideals'],
    vibes: ['Bittersweet','Nostalgic','Hopeful','Awkward'],
    paradoxes: ['The Wise Child','The Old Soul','The Brave Coward'],
  },
  Epic: {
    races: ['Human','Demigod','Legend'],
    professions: ['Chosen One','Warlord','Sage','Herald','Protector'],
    alignments: ['Lawful Good','World-ending Evil','Neutral Arbiter'],
    personalityTraits: ['Heroic','Tragic','Magnanimous','Fated','Grand'],
    backgrounds: ['The Prophecy','The Great War','Fallen Kingdom'],
    magicSystems: ['High Magic','Creation Forces','Destruction','Divine Power'],
    socialStandings: ['Avatar','Emperor','Prophet','Legend'],
    powerSources: ['Cosmos','Faith','Destiny','Sacrifice'],
    vibes: ['Grandiose','Vibrant','Dark-Epic','Eternal'],
    paradoxes: ['The Humble God','The Tragic Hero','The Dying Eternal-being'],
  },
  War: {
    races: ['Human','Soldier Species'],
    professions: ['Sergeant','Medic','Scout','General','War Correspondent','Deserter'],
    alignments: ['Patriotic','Traumatized','Pragmatic','Duty-bound'],
    personalityTraits: ['Stoic','Violent','Protective','Cynical','Brave'],
    backgrounds: ['The Front lines','Occupied Territory','Military Academy'],
    magicSystems: ['Tactical Foresight','Destructive Channeling','Martial Prowess'],
    socialStandings: ['Officer','Grunt','Survivor','Casualty'],
    powerSources: ['Discipline','Rage','Chain of Command','Survival'],
    vibes: ['Bleak','Tense','Industrial','Desperate'],
    paradoxes: ['The Pacifist Soldier','The Kind Warlord','The Fearful Brave-man'],
  },
  Spy: {
    races: ['Human'],
    professions: ['Handler','Mole','Specialist','Asset','Interpol Agent'],
    alignments: ['Deceptive','Loyal (to whom?)','Neutral','Patriotic'],
    personalityTraits: ['Charming','Invisible','Calculating','Adaptable','Paranoid'],
    backgrounds: ['Intelligence Training','Field Op','Bureaucracy'],
    magicSystems: ['Identity Theft','Invisibility','Hyper-intuition','None'],
    socialStandings: ['Ghost','Diplomat','Double Agent'],
    powerSources: ['Information','Secrets','Deep Cover','Assets'],
    vibes: ['Sleek','Suspicious','Nocturnal','Calculated'],
    paradoxes: ['The Truthful Spy','The Famous Shadow','The Traitorous Patriot'],
  },
  Heist: {
    races: ['Human','Specialist'],
    professions: ['Mastermind','Wheel-man','Safecracker','Infiltrator','Heavy'],
    alignments: ['Criminal Mastermind','Loyal to the Crew','Self-Serving'],
    personalityTraits: ['Cool-headed','Meticulous','Daring','Resourceful','Smooth'],
    backgrounds: ['High Security Prison','Professional Thief Life','Disgraced Specialist'],
    magicSystems: ['Planning Trance','Object Manipulation','Stealth'],
    socialStandings: ['Public Enemy','Professional Thief','Underworld Legend'],
    powerSources: ['The Plan','The Crew','The Gear','Precision'],
    vibes: ['Sleek','Tense','Urban','Calculated'],
    paradoxes: ['The Moral Thief','The Honest Con-man','The Clumsy Specialist'],
  },
  Mythology: {
    races: ['God','Titan','Demigod','Monster','Heroic Mortal'],
    professions: ['Herald','Guardian of Tartarus','Oracle','Divine Crafter'],
    alignments: ['Fickle','Eternal','Vengeful','Merciful'],
    personalityTraits: ['Prideful','Divine','Capricious','Ancient','Powerful'],
    backgrounds: ['Creation','Golden Age','The Underworld','The Heavens'],
    magicSystems: ['Cosmic Law','Divine Will','Elemental Domain','Fate'],
    socialStandings: ['Olympian','Titan','Mortal','Monster'],
    powerSources: ['Worship','Essence','The Fates','Ancestry'],
    vibes: ['Celestial','Ancient','Primal','Divine'],
    paradoxes: ['The Mortal God','The Weak Titan','The Foolish Sage'],
  },
};

